### ISSUE TITLE
Implement more ways of activating plugin

### ISSUE THREAD

**Issue by kpj** [boxed/pytest-readme#1]
This is a great plugin, I find it very useful!

While modifying `conftest.py` is a reasonable way of using pytest plugins, it would be nice to enable it via a commandline parameter when executing pytest.
This is also how, e.g., [pytest-cov](https://pypi.org/project/pytest-cov/) and [pytest-pep8](https://pypi.org/project/pytest-pep8/) do it. They can both be activated by calling `pytest --pep8 --cov=myproj`.
It would be nice to simply call `pytest --test-readmes` to automatically test code in readmes.

What do you think?

**Comment by boxed** [comment]
It could just be active if installed. Then you'd not need the flag or the conf file. Seems nicer no?

**Comment by kpj** [comment]
Agreed, that would be a super easy way of using the plugin!
Would it then simply test `README.md` in the project's root directory?

I also found [pytest-markdown](https://github.com/Jc2k/pytest-markdown) which seems to simply test all markdown files it can find.

**Comment by boxed** [comment]
Yea... I've personally mostly moved on from this with some very custom code in iommi. We might polish that so it's generally useful at some point. (That code is for rest, not markdown)

**Comment by kpj** [comment]
Thanks for the feedback! In that case I'll see how far I can get with `pytest-markdown`.
